---
- name: "Install Apt Packages"
  become_user: root
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items: 
    - "{{ apt_packages }}"

- name: "Install Snap Packages"
  become_user: root
  become: true
  community.general.snap:
    name: "{{ item }}"
    state: present
    classic: yes
  with_items: 
    - "{{ snaps }}"
